### ISSUE TITLE
How/where will data be stored for the workshop

### ISSUE THREAD

**Issue by AdeleLip** [michellab/BioSimSpaceTutorials#3]
Since we are not running live simulations themselves and will be using prepared data for the analysis parts of the workshop, I was wondering where it will be stored and how much space we have? For my last part, I would illustrate the start of MSM building, but that requires featurising 100s of 100 ns trajectories (~ 1GB per dry trajectory).

Another concern with that that I have is that it can take a while for the featurisation to be executed - would it be better to use less trajectories as an example or just explain the code without running it (could have saved output in the notebook for illustration).

**Comment by lohedges** [comment]
Since it's just a show-and-tell I think it would be fine to use analyse the data wherever it's located. (Suggesting where it would located for the purposes of a UCB user when reproducing the workflow themselves.)

If you can still get informative results using less trajectories then I'd be fine with stripping down the data set for the purposes of the workshop, e.g. if it's useful for explaining what's going on, what the data looks like, etc. If it's not that important, then it would also be okay just to simply show what the actual output of the analysis looks like, e.g. if it was just the case of hitting go and waiting for the plots to be generated. I don't think we need to do everything in real-time and it could be good to provide an indication of how long the individual stages typically take so the user can plan their coffee breaks.

**Comment by AdeleLip** [comment]
Since we're note actually building the model, I think using a couple trajectories to illustrate what it looks like would be best, and then mention that it of course will take more time with full data. Thanks!
